### ISSUE TITLE
 6. feladat diagram bevitelének problémája 

### ISSUE THREAD

**Issue by takacsflora93** [PE-MK-JAKI-H/MAEK#10]
[MAEK.pdf](https://github.com/PE-MK-JAKI-H/MAEK/files/4603300/MAEK.pdf)
[tablazat.txt](https://github.com/PE-MK-JAKI-H/MAEK/files/4603301/tablazat.txt)
[tablazat2.txt](https://github.com/PE-MK-JAKI-H/MAEK/files/4603303/tablazat2.txt)

Tisztelt Tanár Úr!

Jelenleg  a fent csatolt pdf szerint néz ki a beadandóm. Szeretnék segítséget kérni a két táblázatban.
A diffúzornál nem tudom beállítani a szöget. A hatásfoknál pedig megakadtam a szerkesztésben.Nem tudom milyen parancssorral tudnám szépen bevinni a a görbéket. A görbéhez tartozó adatokat a google táblázatban megadott könyvből szedtem ki.

Köszönöm a segítséget!
Takács Flóra

**Comment by Szalay** [comment]
A beadandódat a GitHub Desktopból a módosított/módosult fájlok kiválasztásával és a pillantfelvétel/commit gombbal tudod beküldeni (https://www.facebook.com/photo?fbid=3117945564912033&set=gm.2709381805961495), nem így kézzel, fájlonként. A forrás nélkül nem igazán tudom megválaszolni a kérdéseid. 

Ha már megnéztem, leírom, hogy milyen hibákat látok:
1) A Bernoulli-egyenlet kötőjeles.
2) A feladat szövege és a megoldás között legyen valamilyen tagolás, mondjuk a Diffúzor definíciója sorból legyen `\subsubsection*`, és a szövege inkább "A diffúzorok tulajdonságai" legyen.
3) Az ábrán még dolgozni kell. A műszaki rajz szabályait többé-kevésbé követnie kellene, és nincs középre igazítva, aminek az okát a forrás nélkül csak sejteni tudom. Hiányzik a `\centering` parancs a `figure` környezetből? W_M jelöléssel még nem találkoztam az áramlástanban. 
5) Az ábra után jöhet a követkető alalszakasz "Veszteséges áramlás a diffúzorokban" címmel.
4) A veszteségmentes Bernoulli-egyenletet lehet a veszteségesből "levezetni", de az csak egy lépés: a veszteség kihagyása. A diffúzornál a veszteséges Bernoulli-egyenletből lehet indulni, mert az egy olyan alapegyenlet, amit mindenkinek tudni kellene.
5) A zárójelek méreteződnek a tartalomhoz, ha a `left[ ... \right]` parancsokkal szeded őket.
6) A sűrűség `\varrho` legyen! A veszteségtényező jele nem ξ, hanem ζ.
7) A nyomásváltozás és a nyomásveszteség nem ugyanaz. A nyomásveszteséget meg lehet említeni, de az energia alapú tárgyalásmód szerint dolgozz! És a betűkhöz tartozó nevek ne változzanak meg menet közben!
8) A diffúzorhatásfok egy szó, és ez lehet harmadik alalszakasz.
9) Az ábrán a diffúzor nyílásszöge alfa, a táblázatban viszont fí.
10) A táblázat utáni részben keverednek a diffúzoros és a csővezetékrendszeres összefüggések, illetve a tömegfajlagos energia alapú és az súlyfajlagos energia (=magasság) alapú tárgyalásmód.

Ui.: A parancssor a cmd.exe, TeX-ben parancsok vannak. Illetve igazából makró a nevük, de az nem segít megérteni őket.
