### ISSUE TITLE
fqsn8q 1.1 feladat kész

### ISSUE THREAD

**Issue by otilia98** [PE-MK-JAKI-H/MAEK#11]

**Comment by Szalay** [comment]
Átnéztem, az észrevételeim:
1) Ez még csak az egyik feladatod, annak is csak az egyik 25 pontos része.
2) Tartalmilag rendben van a megoldás, csak apróbb formai hibákat találtam.
3) A differenciálokban az álló d betű a `\dif` legyen!
4) A második rész ne felsorosolá, hanem folyó szöveg legyen!
5) A kettős integrál az `\iint`, a hámas integrál az `\iiint`. 
6) A sűrűség `\varrho` legyen.
7) Az első és a negyedik integrálban fölösleges a szorzásjel.

A fenti hibák javítása után ez a feladatrész kész.

**Comment by Szalay** [comment]
Összesen csak 75 pontnyi feladatot választottál. A tárgyat ennyivel is lehet teljesíteni, de legfeljebb 4-est tudsz elérni.

**Comment by Szalay** [comment]
Válaszoltam a MHEK tároló Issue-inál.
