### ISSUE TITLE
Biró Bence feladatmegoldás

### ISSUE THREAD

**Issue by birobence1** [PE-MK-JAKI-H/MAEK#12]
Tisztelt Tanár Úr !
 Elkészítettem a választott feladatot, első ellenőrzésre szeretném beadni. 

\section*{5.2.2. A lendületmegmaradás könyökcsőben}

% Hozzáadás a tartalomjegyzékhez adott címmel
\addcontentsline{toc}{section}{18. feladat: }

% Személyes adatok
\begin{tabular}{| p{2cm} | p{14cm} |}
	\hline
	Szerző & Biró Bence AXYX0G \\
	\hline
	Szak & Mechatronikai Mérnök Alapszak\\
	\hline
	Félév & 2019/2020 II. (tavaszi) félév \\
	\hline
\end{tabular}
\vspace{0.5cm}

% Feladat szövege
Alkalmazza a lendületmegmaradást egy függőleges síkban elhelyezkedő, nehézségi erőtérben lévő csőkönyökbeli állandósult áramlásra, ha ismert a belépő oldali $\bar{v}_1$ átlagsebesség és $p_1$ átlagnyomás, a kilépő oldali $\bar{v}_2$ átlagsebesség és $p_2$ átlagnyomás, valamint adottak a csőkönyök méretei! Mit határozhatunk meg a tétel alkalmazásával? Készítsen vázlatot a csőkönyökről és rajzoljon külön a ható erőkről vektorábrát!

% Feladat megoldása

\begin{figure}[!ht]
	\centering
	\label{figure:sm}
	\begin{tikzpicture}
	%	\draw[step=1cm, gray, very thin] (-8, -5) grid (8, 5);
	
	%Alsó harmad
	\draw[thick] (-3, -4) -- (-3, -1); %Bal 
	\draw[thick, dashed] (-2.8, -3.8) -- (-2.8, -1); %Bal szaggatott
	
	
	\draw[thick] (-1, -4) -- (-1, -1); %Jobb
	\draw[thick, dashed] (-1.2, -3.8) -- (-1.2, -1); %Jobb szaggatott
	
	\draw[thick] (-2, -4) -- (-2, -1); %Közép
	
	\draw[thick] (-3, -4) -- (-1, -4); %Alsó
	\draw[thick, dashed] (-2.8, -3.8) -- (-1.2, -3.8); %Alsó szaggatott
	
	
	%Középső harmad
	
	\draw [thick] (-3, -1) arc [radius=4, start angle=180, end angle=90]; %Bal körív
	\draw[thick, dashed] (-2.8, -1) arc [radius=3.8, start angle=180, end angle=90]; %Bal szaggatott körív
	
	\draw [thick](-1, -1) arc [radius=2, start angle=180, end angle=90]; %Jobb körív
	\draw[thick, dashed] (-1.2, -1) arc [radius=2.2, start angle=180, end angle=90]; %Jobb szaggatottkörív
	
	\draw[thick] (-2, -1) arc [radius=3, start angle=180, end angle=90]; %Közép körív
	
	%Felső harmad
	\draw[thick] (1, 3) -- (4, 3); %Felül 
	\draw[thick, dashed] (1, 2.8) -- (3.8, 2.8); %Felül szaggatott
	
	\draw[thick] (1, 1) -- (4, 1); %Alul 
	\draw[thick, dashed] (1, 1.2) -- (3.8, 1.2); %Alul szaggatott
	
	\draw[thick] (1, 2) -- (4, 2); %Közép
	
	\draw[thick] (4, 1) -- (4, 3); %Jobb záró 
	\draw[thick, dashed] (3.8, 1.2) -- (3.8, 2.8); %Jobb záró szaggatott
	
	
	
	%Vektorok
	\draw[->, ultra thick] (-2, -4) -- (-2, -3.2)
	node[midway, anchor=north west, xshift={-8mm}, yshift={7mm}]{$\bar{F}_{P_1}$}; %F_P_1 vektor
	\draw[->, ultra thick] (-2, -4) -- (-2, -5)
	node[midway, anchor=north west, xshift={-8mm}, yshift={3mm}]{$\bar{J}_{1}$}; %J_1 vektor
	\draw[-, thick] (-2, -4) -- (-2, -4)
	node[midway, anchor=north west, xshift={12mm}, yshift={3mm}]{$A_1 P_1$};
	%A1 P1 felirat
	
	\draw[->, ultra thick] (-1.5, -4) -- (-1.5, -3.4)
	node[midway, anchor=north west, xshift={-2mm}, yshift={8mm}]{$\bar{V}_{1}$}; %V_1 vektor
	\draw[->, ultra thick] (-1.5, -4) -- (-1.5, -4.6)
	node[midway, anchor=north west, xshift={0mm}, yshift={0mm}]{$\bar{n}_{1}$}; %n_1 vektor
	
	\fill (-2, -4) circle (0.1); %Alsó pont
	
	\draw[->, ultra thick] (-1, 1.2) -- (-1, 0.3)
	node[midway, anchor=north west, xshift={0mm}, yshift={8mm}]{$m_0\cdot\bar{g}$}; %m_0 cdot g
	\fill (-1, 1.2) circle (0.1); %Középső pont
	
	\draw[-, thick] (0, 0.7) -- (0.5, 0)
	node[midway, anchor=north west, xshift={3mm}, yshift={0mm}]{$\partial V_0$}; %/partial V_0 vonal
	
	\draw[->, thick] (-1.5, 3) -- (-1.2, 2.4)
	node[midway, anchor=north west, xshift={0mm}, yshift={5mm}]{$\bar{F}t$}; % Ft vektor
	
	\draw[-, thick] (-2, 2.3) -- (-2, 2.3)
	node[midway, anchor=north west, xshift={-4mm}, yshift={2mm}]{$Ap$}; % Ap felirat
	
	
	\draw[->, thick] (4, 2) -- (3, 2) 
	node[midway, anchor=north west, xshift={-2mm}, yshift={8mm}]{$\bar{F}_{p_2}$}; %Fp2 vektor
	
	
	
	\draw[->, thick] (4, 2) -- (6, 2) 
	node[midway, anchor=north west, xshift={-2mm}, yshift={6mm}]{$\bar{J}_{2}$}; %J2 vektor
	
	\draw[->, thick] (4, 1.5) -- (3, 1.5) 
	node[midway, anchor=north west, xshift={-10mm}, yshift={3mm}]{$\bar{n}_2$}; %p2 vektor
	
	\draw[->, thick] (4, 1.5) -- (5.5, 1.5) 
	node[midway, anchor=north west, xshift={6mm}, yshift={3mm}]{$\bar{v}_{2}$}; %v2 vektor
	
	\draw[-, thick] (4, 3.5) -- (4, 3.5)
	node[midway, anchor=north west, xshift={-3mm}, yshift={3mm}]{$A_2 P_2$}; % A2P2 felirat
	\draw[>-<, thick] (2,0.7) -- (2,3.3) node[midway, anchor=north west, xshift={-5mm}, yshift={5mm}]{$D$};
	
	
	\fill (4, 2) circle (0.1); %Felső pont
	
	\end{tikzpicture}
	\caption{Függőleges síkban elhelyezkedő, nehézségi erőtérben lévő csőkönyök}
\end{figure}
\pagebreak

Minta számítás az erővektorábra elkészítéséhez , a H3/6-os feladat alapján. \par
$\dot{v} = \SI[per-mode=symbol]{50}{\liter\per\second} =  \SI{0.05}{\meter^{3}\per\second} $\par
$p_1 = \si{1,2} $ bar\par
$\alpha = \si{90}^{\circ}$\par
$D = \SI{0.15}{\meter}$\par
$h =  \SI{0.3}{\meter}$\par
$p_0 = \si{1} $ bar\par
$\varrho_v =  \SI[per-mode=symbol]{1000}{\kilogram\per\meter^{3}}$\par
$m_0 = \SI{3}{\kilogram}$\par 

\begin{equation*}
	\bar{J}_{be}+\bar{J}_{ki} = 
	\bar{F}_{p_1} + \bar{F}_{p_2} + \bar{F}_{t}
\end{equation*}

\begin{equation*}
v_1 = \dfrac{\dot{V}}{A} = \dfrac{\dot{V}}{\dfrac{D^2\pi}{4}} = 
\SI{2.83}{\meter\per\second} 
\end{equation*}

\begin{equation*}
v_1 = v_2
\end{equation*}

\begin{equation*}
	\dot{m} = \varrho\cdot\dot{v} = \SI[per-mode=symbol]{50}{\kilogram\per\second}
\end{equation*}

\begin{equation*}
	\bar{J}_{be} = 
	\dot{m}\cdot \bar{v}_1 = \SI{141.5}{\newton}
\end{equation*}

\begin{equation*}
	\bar{J}_{ki} = 
	\dot{m}\cdot \bar{v}_2 = \SI{141.5}{\newton}
\end{equation*}

\begin{equation*}
	\bar{F}_{p_1} = 
	\left( p_1 - p_0 \right) \cdot A = 	\left( p_1 - p_0 \right) \cdot 
	\dfrac{D^2 \pi}{4} = \SI{353.4}{\newton}
\end{equation*}

Túlnyomásból származó erő
\begin{equation*}
	\cancel{\dfrac{{v_1}^2}{2}} + \dfrac{p_1}{\varrho} + \cancel{gz_1} =
	\cancel{\dfrac{{v_2}^2}{2}} + \dfrac{p_2}{\varrho} + gz_2
\end{equation*}

\begin{equation*}
v_1 = v_2 \hspace{0.5cm}
v_2 = v_1
\end{equation*}
\begin{equation*}
z_1 = \SI{0}{\meter} \hspace{0.5cm}
z_2 = h
\end{equation*}

\begin{equation*}
	\dfrac{p_1}{s} = \dfrac{p_2}{s} + g\cdot h \rightarrow p_2 =
	p_1 -\left( g\cdot h\cdot\varrho_v \right) = \SI{117057}{\pascal}
\end{equation*}

\begin{equation*}
	\bar{F}_{p_2} = 
\left( p_2 - p_0 \right) \cdot A = 	\left( p_2 - p_0 \right) \cdot 
\dfrac{D^2 \pi}{4} = \SI{301.4}{\newton}
\end{equation*}

\begin{equation*}
	\bar{F}_{t} = 
	\sqrt{\left( J_{be} + F_{p_1}\right)^2 + 
	\left( J_{ki} + F_{p2} \right)^2} - m_0\cdot g = \SI{634.7}{\newton}
\end{equation*} \par 

\pagebreak
Lépték: $\SI{100}{\newton} = \SI{2}{\centi\meter}$\par
$\bar{J}_{be} = \SI{2.83}{\centi\meter}$ \par
$\bar{J}_{ki} = \SI{2.83}{\centi\meter}$\par
$\bar{F}_{p_1} = \SI{7.068}{\centi\meter}$\par
$\bar{F}_{p_2} = \SI{6.028}{\centi\meter}$\par
$m_0\cdot g = \SI{0.588}{\centi\meter}$\par
$F_t = \SI{12.694}{\centi\meter}$\par

\begin{figure}[!ht]
	\centering
	\label{figure:sm}
	\begin{tikzpicture}
%	\draw[step=1cm, gray, very thin] (-8, -6) grid (8, 6);

	
	\draw[->, thick] (2, 5) -- (-4.028, 5) 
	node[midway, anchor=north west, xshift={-2mm}, yshift={6mm}]{$\bar{F}_{p_2}$}; %Fp_2 vektor
	
	\draw[->, thick] (-4.028, 5) -- (-4.028, 4.412) 
	node[midway, anchor=north west, xshift={-14mm}, yshift={2mm}]{${m_0}\cdot g$}; %m_0 g szorzat
	
	\draw[->, thick] (2, -2.068) -- (2, 5) 
	node[midway, anchor=north west, xshift={0mm}, yshift={6mm}]{$\bar{F}_{p_1}$}; %Fp_1 vektor
	
	\fill (2, -2.068) circle (0.1); %FP1 Jbe metszéspont
	
	\draw[->, thick] (2, -2.068) -- (2, -4.898) 
	node[midway, anchor=north west, xshift={0mm}, yshift={6mm}]{$\bar{J}_{be}$}; %J_be vektor
	
	\draw[->, thick] (2, -4.898) -- (4.83, -4.898) 
	node[midway, anchor=north west, xshift={0mm}, yshift={6mm}]{$\bar{J}_{ki}$}; %J_be vektor
	
		\draw[->, thick] (-4.028, 4.412) -- (4.83, -4.898) 
	node[midway, anchor=north west, xshift={0mm}, yshift={6mm}]{$\bar{F}_{t}$}; %F_t vektor
	
	\end{tikzpicture}
	\caption{Erővektor}
\end{figure}

\pagebreak

\underline{Elhanyagolások:} \par
\vspace{0.5cm}

$\varrho =$ állandó , $\bar{f} = \bar{g}$ (nehézségi erőtér), $j$ állandósult állapot \par
\vspace{0.5cm}

\begin{equation*}
	\cancel{\dfrac{\partial}{\partial t}
	\int\limits_{V_0}^{} \varrho\bar{v}\mathrm{dV}} + 
	\oint\limits_{\partial	V_0}^{}\varrho\bar{v}\left(\bar{v}\cdot\mathrm{d}\bar{A}\right) = 
	\int\limits_{V_0}^{}\varrho\bar{f}\mathrm{dV} - 
	\oint\limits_{\partial V_0}^{} p \cdot \mathrm{d}\bar{A} + 
	\cancel{\oint\limits_{\partial V_0}^{}\bar{\bar{\tau}}\mathrm{d}\bar{A}}
\end{equation*} \par
\vspace{0.5cm}

Magyarázat: \par
Az első tag kiesik, mivel állandósult állapot, illetve a csúsztató feszültség ($\bar{\bar{\tau}}$) értéke \SI{0}{\pascal}\par
\vspace{0.5cm}

\begin{equation*}
	\oint\limits_{\partial V_0}^{}\varrho\bar{v}\left(\bar{v}\cdot\mathrm{d}\bar{A}\right) = 
	\int\limits_{A_1}^{}\varrho\bar{v}\left(\bar{v}\cdot\mathrm{d}\bar{A}\right) + 
	\int\limits_{A_P}^{}\varrho\bar{v}\left(\bar{v}\cdot\mathrm{d}\bar{A}\right) + 
	\int\limits_{A_2}^{}\varrho\bar{v}\left(\bar{v}\cdot\mathrm{d}\bar{A}\right)
\end{equation*} \par
\vspace{0.5cm}

Az egyenlet kifejtve: \par
\vspace{0.5cm}

\begin{equation*}
	\oint\limits_{\partial V_0}^{}\varrho\bar{v}\left(\bar{v}\cdot\mathrm{d}\bar{A}\right) = 
	\bar{J}_1 + 0 + \bar{J}_2 = 
	-\dot{m}\cdot\bar{v}_1 + 
	\dot{m}\cdot\bar{v}_2
\end{equation*}

\begin{equation*}
	\bar{J}_1 =
	\bar{v}_1\int\limits_{A_1}^{}\varrho\bar{v}\cdot\mathrm{d}\bar{A} = 
	-\dot{m}\cdot\bar{v}_1
\end{equation*}

\begin{equation*}
	\oint\limits_{\partial V_0}^{}p\mathrm{d}\bar{A} = 
	\int\limits_{A_1}^{}p\mathrm{d}\bar{A} + 
	\int\limits_{A_P}^{}p\mathrm{d}\bar{A} + 
	\int\limits_{A_2}^{}p\mathrm{d}\bar{A} 
\end{equation*} 

Az egyenlet kifejtve: \par
\vspace{0.5cm}

\begin{equation*}
	\oint\limits_{\partial V_0}^{}p\mathrm{d}\bar{A} =
	-\bar{F}_{P_1} + \bar{F}_T + \bar{F}_{P_2}
\end{equation*} \par
\vspace{0.5cm}

\begin{equation*}
	-\bar{F}_{P_1} = 
	-p_1\bar{A}_1 =
	-p_1\cdot\bar{n}_1\cdot A_1
\end{equation*} \par
\vspace{0.5cm}

\begin{equation*}
	\bar{F}_{P_2} = - p_2\bar{A}_2 =
	-p_2\cdot\bar{n}_2\cdot A_2
\end{equation*} \par
\vspace{0.5cm}

\begin{equation*}
	\bar{J}_1 + \bar{J}_2 =
	-m_0\cdot\bar{g} + \bar{F}_{P_1} + \bar{F}_T + \bar{F}_{P_2}
\end{equation*} \par
\vspace{0.5cm}

A kapott értékeket behelyettesítve a következő egyenletet kapjuk:

\begin{equation*}
	-\dot{m}\cdot\bar{v}_1 + \dot{m}\cdot\bar{v}_2 = 
	m_0\cdot\bar{g} - p_1\bar{A}_1 + 
	\bar{F}_T - 
	p_2\bar{A}_2
\end{equation*} \par
\vspace{3.5cm}

% Oldaltörés
\pagebreak
[axyx0g.txt](https://github.com/PE-MK-JAKI-H/MAEK/files/4636085/axyx0g.txt)

**Comment by Szalay** [comment]
Látom, hogy fel van töltve, nem kellett volna bemásolni.

**Comment by Szalay** [comment]
Átnéztem, a következő kisebb javítani valók vannak:
1) A vektorokat `\vec`-cel szedd. Az összeset. Minden egyenletben és a szövegben is. Van a TeXstudioban keresés és csere.
2) A mennyiségek jelöléseit az áramlsátan beugrónál megadottakhoz kellene igazítani: a nyomás kis p, a sebesség kis v, a térfogatáram nagy \dot{V}.
3) Sok a fölösleges szorzásjel. Szerencsére a skalárszozatokat viszont mind jelölted.
4) A könyök ábráját kicsit a műszaki rajz, kicsit az ésszerűség irányába kellene javítani: a külső körvonal vastag, a végein karima, az ellenőrző felület olyan közel a falhoz, amennyire lehet, a D-nél lemaradt a `\diameter`, a végeknél A és p felsorolás, nem szorzat, a vektorok nyilai `ultra thick` vastagok legyenek.
5) Az erővektoros ábrán a g is legyen vektor, és ne erővektor legyen az ábnra felirata!

Egy komolyabb változtatásra lenne szükség: két három egyenlet után kellene egy-egy magyarázó mondat, arról, hogy mi történik.
