### ISSUE TITLE
fqsn8q 1.1 feladat javítva

### ISSUE THREAD

**Issue by otilia98** [PE-MK-JAKI-H/MAEK#13]
Tisztelt Tanár úr!

Az integrálokat, differenciálok esetén a d betűket és a további problémát kijavítottam. Úgy tudom, hogy ez a feladat így készen van, a másik feladatom 25+25 pontos, ha készen van hozzájuk az ábra is. A kérdésem az, hogy a korábbi üzenetében erre gondolt, vagy valamilyen feladat mellett elsiklottam?

Válaszát előre is köszönöm.

Tisztelettel, 
Tóth Otília

**Comment by Szalay** [comment]
Válaszoltam a MHEK tároló Issue-inál. https://github.com/PE-MK-JAKI-H/MHEK/issues/7
