### ISSUE TITLE
fqsn8q 1.1 feladat 2. része is elkészült

### ISSUE THREAD

**Issue by otilia98** [PE-MK-JAKI-H/MAEK#14]
Tisztelt Tanár úr!

A feladat második 25 pontos részét is elkészítettem, amit korábban nem láttam. 

Tisztelettel,
Tóth Otília

**Comment by Szalay** [comment]
Válaszoltam a MHEK tároló Issue-inál. https://github.com/PE-MK-JAKI-H/MHEK/issues/7
