### ISSUE TITLE
AXYX0G 2. ellenőrzés 

### ISSUE THREAD

**Issue by birobence1** [PE-MK-JAKI-H/MAEK#15]
Tisztelt Tanár Úr ! 

Csatolva küldöm a megoldásomat második ellenőrzésre. 

[megoldas_v2.txt](https://github.com/PE-MK-JAKI-H/MAEK/files/4661593/megoldas_v2.txt)

**Comment by Szalay** [comment]
Elvileg az utolsó feltöltésed frissebb, mint a csatolt fájl, úgyhogy azt ellenőriztem. Az eredményt megtalálod a Google-táblázatban.
