### ISSUE TITLE
6/3 feladat

### ISSUE THREAD

**Issue by SturmReni** [PE-MK-JAKI-H/MAEK#16]
Kedves Tanár úr!

Elkészítettem a 6/3. feladatot (Bernoulli egyenlet veszteséges és veszteségmentes alakja), le tudná ellenőrizni?

Köszönöm,
Sturm Renáta  (EQSJGB)

**Comment by Szalay** [comment]
Ezt az issue-t lezártam, és a másik feladatodnál válaszoltam az MAFGY-nél.
