### ISSUE TITLE
6.-8. feladat végleges feltöltés előtti ellenőrzésre

### ISSUE THREAD

**Issue by takacsflora93** [PE-MK-JAKI-H/MAEK#17]
Tisztelt Tanár Úr!

18.-án feltöltöttem a lehetőleg végleges verziót. A javításokat, amit kért igyekeztem a legjobban elvégezni. Szeretnék kérni egy felül vizsgálatot, hogy ez a minőség meg felel-e a megajánlott jegynek ? 
A megjegyzés ellenére a Bernoulli- egyenlet levezetését nem tudtam másképpen felírni, más szakirodalmi forrás hiányában.  
Előre is köszönöm !

Üdvözlettel,
Takács Flóra

**Comment by Szalay** [comment]
Átnéztem és pontoztam a jelenlegi állapot alapján, az eredményt megtalálod a Google-táblázatban.

Ha szeretnél javítani a beadandón, akkor írok egy listát a hibákról.

**Comment by takacsflora93** [comment]
Köszönöm szépen! A vizsgák és a munka elviszik az időm, emiatt szeretném kérni a megajánlott jegyet és nem élnék a javítás lehetőségével.
Szeretném kérdezni, hogy a végleges verziót, amit majd a tanár úr felhasznál az oktatás során (teljes tananyag) lenne-e rá lehetőség, hogy a másolatát megkapjam? Különösen érdekelnek a számítások. [A munkahelyemen (Zoltek Zrt.) lehetőséget kaptam, több terület feltérképezésére, mint projekt és szeretném, ezt alapnak használni.]

**Comment by Szalay** [comment]
Felírtam, hogy elfogadtad a négyest. Vizsgára jeelntkezni ne felejts el, mert vizsgajegyként tudom megadni a jegyet (Neptun valószínűleg hagyná, hogy visszadátumozzam a megajánlott jegyet, de hivalatosan azt a szorgalmi időszak végéig adhatok csak).

Az még nem tudom megmondani, hogy mikor lesz időm egyesíteni a megoldott feladatokat, illetve előtte még megkérdezem az érintetteket, hogy van-e kifogásuk a munkájuk felhasználása ellen. És ha te fel akarod hazsnálni, akkor neked is ezt kell tenni. Megnézni persze megtudod mindenki megoldását, de a felhasználás, főleg úgy, hogy utána fizet érte a cég, az egy nagyon más történet.
