### ISSUE TITLE
5.2-es feladat ellenőrzés

### ISSUE THREAD

**Issue by listvan247** [PE-MK-JAKI-H/MAEK#19]
Tisztelt Tanár Úr!

Feltöltöttem az 5.2-es feladatot az MDGT1V branch-re, kérem ellenőrizze.
Illetve azt szeretném kérdezni, hogy elégséges-e a megoldásom, vagy még javítanom kell rajta?
Válaszát előre is köszönöm.

**Comment by Szalay** [comment]
Átnéztem és pontoztam, az eredményt megtalálod a Google-táblázatban. Javítani nem kötelező, de lehet. Ha szeretnél javítani a beadandón, akkor írok egy listát a hiányosságokról.
