### ISSUE TITLE
Fejezet szám tex vs google sheet

### ISSUE THREAD

**Issue by molnargreta** [PE-MK-JAKI-H/MAEK#2]
A MAEK .tex file-ban a fejezet számom, ahová a feladatomat importálnom kell, az azt írja, hogy 2. fejezet, de a google sheet dokumentumban a feladatom az 5/4-es.
![image](https://user-images.githubusercontent.com/63009004/78587273-fdd22500-783c-11ea-990e-e9e8d9060078.png)

Hogyan számozzam a feladatomat, maradjon simán 5/4, esetleg K5/4 vagy elméleti kérdésekhez valami más számozást használjunk?

**Comment by Szalay** [comment]
Ez egyelőre maradhat így. A 2/3/4-es fejezetek elméleti kérdéseit már kidolgoztam korábban az áramlástan jegyzetben, azért maradtak ki.

**Comment by molnargreta** [comment]
Rendben, köszönöm szépen.
