### ISSUE TITLE
5.1-es kérdés ,  lendületmegmaradás alkalmazása

### ISSUE THREAD

**Issue by birobence1** [PE-MK-JAKI-H/MAEK#5]
![20200409_145042](https://user-images.githubusercontent.com/63041746/79041611-66c8ec80-7bf1-11ea-9ff6-24e1899dddd4.jpg)
![20200409_145031](https://user-images.githubusercontent.com/63041746/79041612-6892b000-7bf1-11ea-8e30-0043727d3a46.jpg)
Tanár Úr ellenőrzését / kiegészítését szeretném kérni.

**Comment by Szalay** [comment]
A megoldás alapvetően jól indul, a kérdésre ad válaszokat. Appróbb hibából viszont van jónéhány.

1) A jobb felső sarokban a nyomóerők egyenleteinél bal oldalon vektorok vannak, a jobb oldalon nem. Hiányoznak a normálvektorok, és a megfelelő előjel. És a normálvektorok a könyök ábrájáról is hiányoznak. 

2) A könyök ábráján nem térfogatáramokat (\dot{V}_1 és \dot{V}_2), hanem átlagsebesség-vektorokat kellene megjelölni. A térfogatáram nem is vektor. 

3) Az erővektorábrán a nyomóerők is legyenek vektorok (lemaradt fölülük a jelölés), ugyanez történt az utolsó előtti egyenletben az impulzuserőkkel.

4) Az elhanyagolások jók. Az integrális alakban az impulzuserőket kifejező mozgási deriváltból hiányzik a skalárszorzat jelölése.

5) A főbb lépésekhez kellene majd fogalmazni magyarázatokat.

6) A két ábra elkészítése előtt egy mintaszámítást kellene végezni, hogy a vektorok hosszai egy való áramlás viszonyainak megfeleljenek. Ez történhet a veszteségmentes Bernoulli-egyenletet felhasználva. Mintául szolgálhatnak a H3/6-os feladat számai. Ez a számítás beleszámítana az ábrák értékelésébe.
