### ISSUE TITLE
5/4 ellenőrzés

### ISSUE THREAD

**Issue by molnargreta** [PE-MK-JAKI-H/MAEK#7]
Kijavítottam mindent amit kért a [legutolsó pull requestemben](https://github.com/PE-MK-JAKI-H/MAEK/pull/6).
Kérem ellenőrizze.

**Comment by Szalay** [comment]
A megjegyzéseket a forráshoz írom, a megfelelő sorhoz.

**Comment by Szalay** [comment]
Átnéztem, még mindig sok az apróbb hiba, és az ábrával elégetlen vagyok. Ráadásul ez csak 75 pontos feladat, lehet, hogy egy 25-öst még keresned kellene. Vagy ha rajzolsz paraméterezhető ábrát, akkor megnövelem ezt a feladatot 100 pontosra.

**Comment by molnargreta** [comment]
Az apróbb hibákat kijavítottam, az ábrát pedig megpróbálom átrajzolni paraméterezhetővé.
Amíg nincs újra ellenőrizhető ábrám, addig ezt az issue-t átrakom "válaszoltam" label-re.

**Comment by molnargreta** [comment]
Átalakítottam az ábrát paraméterezhetőre és kiegészítettem pár mondattal az egyenleteket ahol kérte.
Kérem ellenőrizze újra.

**Comment by Szalay** [comment]
Ellenőriztem a feladatot és most már pontoztam is. A Google-táblázatban megtalálod a részletes bontást. A feladat 75 pontot ér, a jelenlegi állapotban 80 %-ra értékeltem, azaz 75 · 80 % = 60 % az eredmény, erre jön + 10 % a határidő előtti teljesítéssel, azaz a végeredmény a jelenlegi állapotban 66 %. 

Az ábrán vannak még mindig kisebb hibák, illetve nagy általánosságban részletesebb magyarázatokat vártam volna. Amennyiben ezeket szeretnéd javítani, megjelölöm őket.

Jegyet sajnos még nem tudok adni, mert az oktatási dékányhelyettes még nem bólintott rá a beadandó feladat teljesítési feltételeire, de egyébként közepes lenne az eredmény, mert a nálam szokásos 50/60/70/80 százalékos szintek szerint adok jegyet.

**Comment by molnargreta** [comment]
Az előző válaszában azt tetszett írni, hogy ha újra rajzolom az ábrámat paraméterezhetőre, akkor javítja a feladatomat 75 pontról 100 pontosra:
https://github.com/PE-MK-JAKI-H/MAEK/issues/7#issuecomment-615848090

Illetve az ábrán lévő kisebb hibákat szeretném javítani amennyiben ez befolyásolja végleges érdemjegyemet. 
Köszönöm szépen.

**Comment by Szalay** [comment]
Ez jogos észrevétel, mindjárt javítom magam :)

**Comment by Szalay** [comment]
Az ábrát tényleg átalakítottad, úgyhogy előszöris javítotam a feladatkiírást.

A javítandó részletek a következők:
1) A felszín jele üres háromszög legyen.
2) A t_0 = 0 s felirat felesleges.
3) A dV_1 alatti idő t+dt, a mélység pedig h+dh legyen, és a h tengelynek legyen talpa a 0 m-es mélységnél, azaz fent.
4) A feladat legvégén egy két-három mondatos összefogalaló/megjegyzés jellegű bekezdést kérnék még, a leírja, hogy mi történt, és nagyvonalakban mit kell csinálni a különböző alakú tartályoknál.

Amennyiben ezeket a módosításokat megkapom, a végeredményed 80 % fölé megy.

**Comment by molnargreta** [comment]
Elvégeztem a kért javításokat, kérem ellenőrizze.

**Comment by Szalay** [comment]
Nem egészen úgy oldottam meg a végét, ahoigy gondoltam, de ettől függetlenül rendben van. A végleges pontozást megtalálod a Google-táblázatban.
