### ISSUE TITLE
6. feladat Vázoljon fel egy diffúzort. 8. feladat Egyenértékű csőhosszúság.

### ISSUE THREAD

**Issue by takacsflora93** [PE-MK-JAKI-H/MAEK#8]
Tisztelt Tanár Úr!

Elkészítettem a 6. és 8. feladatot előzetesen kézzel. Szeretném kérni az átnézését javításra, továbbá nem tudom milyen módon kellene arra a kérdésre válaszolni, hogy milyen kapcsolat van a hatásfok és a veszteség tényező (diffúzor) között. Mivel egy egyik a Bernoulli levezetés a másik pedig egy kísérletileg meghatározott összefüggés. Ebben is szeretném a segítségét kérni.

Köszönöm szépen,
Takács Flóra

[beadando-wt08a8.pdf](https://github.com/PE-MK-JAKI-H/MAEK/files/4497251/beadando-wt08a8.pdf)

**Comment by Szalay** [comment]
Tartalmilag mindkét feladat elfogadható szinten van, a hatosnál kérném csak, hogy egészítsd ki az \eta_D és az Y_{veszt} kapcsolatával. Az elektronikus változatban elegendő lesz két ábrát elkészíteni, egyet a diffúzorról és egyet diffúzor hatásfokról. Ez utóbbihoz keresni kellene adatot vagy közelítő egyenletet (a Google táblázatban adtam forrást).

**Comment by Szalay** [comment]
A Google-táblázat frissítése közben észrevettem, hogy 125 pontnyi feladatot foglaltál le magadnak, ami több mint 100 :) úgyhogy, amennyiben nincs ellenvetésed, a diffúzor hatásfokos rész pontszámát visszavettem 25-re, és hogy a feladat is kevesebb legyen, ne csak a pont, amikor elérsz ehhez a részhez, jelentkezz, és segíteni fogok.
